#!/bin/sh

REPO=piku235/mobilus-gtw-runtime
PACKAGE_NAME="runtime.tar.gz"
PACKAGE_URL="https://github.com/$REPO/releases/latest/download/$PACKAGE_NAME"
RUNTIME_DIR=/opt/jungi
PACKAGES_DIR=$RUNTIME_DIR/packages

run_script() {
    script=$1

    if [ -x "$script" ]; then
        "$script"
        rc=$?

        if [ $rc -ne 0 ]; then
            exit $rc
        fi
    fi
}

rollback_mobilus() {
    echo "Rolling back mobilus"
    /etc/init.d/mobilus disable
    /etc/init.d/mobilus stop
    
    rm -f /etc/init.d/mobilus
    [ -f /etc/rc.local.old ] && mv /etc/rc.local.old /etc/rc.local
    /mobilus/mobilus &
}

update() {
    if [ ! -d $RUNTIME_DIR ]; then
        echo "runtime is not installed"
        exit 1
    fi

    tempdir=$(mktemp -d)

    cleanup() {
        [ -n "$tempdir" ] && rm -rf "$tempdir" || true
    }

    trap cleanup EXIT

    wget -qO "$tempdir/$PACKAGE_NAME" --no-check-certificate "$PACKAGE_URL"

    if [ $? -ne 0 ]; then
        echo "Failed to download the runtime"
        exit 1
    fi

    echo "Extracting the runtime"
    gzip -dc "$tempdir/$PACKAGE_NAME" | tar -xf - -C $tempdir .

    if [ $? -ne 0 ]; then
        echo "Failed to extract the runtime"
        exit 1
    fi

    current_version=$(cat $RUNTIME_DIR/.runtime/version)
    package_version=$(cat $tempdir/.runtime/version)

    if [ $current_version = $package_version ]; then
        echo "Already at the lastest v$current_version"
        exit 1
    fi

    echo "Updating to version $package_version"
    run_script "$tempdir/.runtime/preinst"
    run_script "$RUNTIME_DIR/.runtime/prerm"

    echo "Removing obsolete files"
    [ -f "$RUNTIME_DIR/.runtime/files" ] && while read f; do
        source="$RUNTIME_DIR/$f"
        if [ ! -e "$tempdir/$f" ]; then
            rm -f "$source"
            echo "$source"
        fi
    done < "$RUNTIME_DIR/.runtime/files"
    rm -f "$RUNTIME_DIR/.runtime/files"

    echo "Updating files"
    find "$tempdir/files" \( -type f -o -type l \) ! -path '*/.*' | while read f; do
        relative="${f#$tempdir/}"
        dest="$RUNTIME_DIR/$relative"

        mkdir -p "$(dirname "$dest")"
        if [ ! -e "$dest" ] || ! cmp -s "$f" "$dest"; then
            cp -a "$f" "$dest"
            echo "$relative"
        fi

        echo "$relative" >> "$RUNTIME_DIR/.runtime/files"
    done

    cp "$tempdir/.runtime/version" "$RUNTIME_DIR/.runtime"
    run_script "$tempdir/.runtime/postinst"
}

remove() {
    if [ ! -d $RUNTIME_DIR ]; then
        echo "runtime is not installed"
        exit 1
    fi

    if find $PACKAGES_DIR -mindepth 1 -maxdepth 1 -type d | read; then
        echo "There are still installed packages, remove them first to remove the runtime"
        exit 1
    fi

    read -p "Are you sure you want to continue? (y/n) " answer
    if [ "$answer" != "y" && "$answer" != "Y" ]; then
        echo "Aborted"
        exit 1
    fi

    run_script "$RUNTIME_DIR/.runtime/prerm"
    rollback_mobilus

    echo "Removing runtime"
    rm -rf "$RUNTIME_DIR"

    run_script "$RUNTIME_DIR/.runtime/postrm"
}

show_usage() {
    cat <<'EOF'
Usage:
    runtime update  # updates the runtime
    runtime remove  # removes the runtime
EOF
}

case "$1" in
    update) shift; update;;
    remove) shift; remove;;
    *) show_usage;;
esac
