name: Release Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      OPENWRT_VERSION: "24.10.3"
      GCC_VERSION: "13.3.0"
      MAIN_TARGET: "ramips"
      SUB_TARGET: "mt76x8"
      ARCH: "mipsel_24kc"

    steps:
    - uses: actions/checkout@v5

    - name: Common strings
      id: strings
      shell: bash
      run: |
        echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "openwrt-target-dir=openwrt-sdk/staging_dir/target-${ARCH}_musl" >> "$GITHUB_OUTPUT"
        echo "openwrt-toolchain-dir=openwrt-sdk/staging_dir/toolchain-${ARCH}_gcc-${GCC_VERSION}_musl" >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y patchelf build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

    - name: Download OpenWRT SDK
      run: |
        wget -q https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${MAIN_TARGET}/${SUB_TARGET}/openwrt-sdk-${OPENWRT_VERSION}-${MAIN_TARGET}-${SUB_TARGET}_gcc-${GCC_VERSION}_musl.Linux-x86_64.tar.zst
        tar -xf openwrt-sdk-${OPENWRT_VERSION}-${MAIN_TARGET}-${SUB_TARGET}_gcc-${GCC_VERSION}_musl.Linux-x86_64.tar.zst
        mv openwrt-sdk-${OPENWRT_VERSION}-${MAIN_TARGET}-${SUB_TARGET}_gcc-${GCC_VERSION}_musl.Linux-x86_64 openwrt-sdk

    - name: Export OpenWRT SDK
      run: |
        echo "PATH=${PWD}/openwrt-sdk/staging_dir/toolchain-${ARCH}_gcc-${GCC_VERSION}_musl/bin:$PATH" >> $GITHUB_ENV
        echo "STAGING_DIR=${PWD}/openwrt-sdk/staging_dir/toolchain-${ARCH}_gcc-${GCC_VERSION}_musl" >> $GITHUB_ENV

    - name: Install SDK feeds
      working-directory: openwrt-sdk
      run: |
        scripts/feeds update -a
        scripts/feeds install -a
        make defconfig

    - name: Compile OpenWRT libraries
      working-directory: openwrt-sdk
      run: |
        make -j$(nproc) package/openssl/compile
        make -j$(nproc) package/mosquitto/compile
        make -j$(nproc) package/sqlite3/compile

    - name: Copy compiled libraries
      run: |
        mkdir -p runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-target-dir }}/usr/lib/libcares.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-target-dir }}/usr/lib/libcjson.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-target-dir }}/usr/lib/libcrypto.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-target-dir }}/usr/lib/libssl.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-target-dir }}/usr/lib/libmosquitto.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-target-dir }}/usr/lib/libmosquittopp.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-target-dir }}/usr/lib/libsqlite3.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-target-dir }}/usr/lib/libz.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-toolchain-dir }}/lib/ld-musl-mipsel-sf.so.1 runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-toolchain-dir }}/lib/libatomic.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-toolchain-dir }}/lib/libc.so runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-toolchain-dir }}/lib/libgcc_s.so* runtime/opt/jungi/lib
        cp -a ${{ steps.strings.outputs.openwrt-toolchain-dir }}/lib/libstdc++.so* runtime/opt/jungi/lib

    - name: Strip compiled libraries
      run: find runtime/opt/jungi/lib -maxdepth 1 -type f -name 'lib*.so*' ! -name 'libgcc_s.so' -exec mipsel-openwrt-linux-strip --strip-unneeded {} +

    - name: Build package
      run: |
        cp -ar scripts runtime/opt/jungi/
        tar -czf runtime.tar.gz -C runtime .

    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        files: runtime.tar.gz
